language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - FACEBOOK_PAGE_ACCESS_TOKEN=YOUR_PAGE_ACCESS_TOKEN
    - FACEBOOK_WEBHOOK_VERIFICATION_TOKEN=YOUR_FACEBOOK_WEBHOOK_VERIFICATION_TOKEN
    - TWITTER_ACCESS_TOKEN_KEY=YOUR_ACCESS_TOKEN_KEY
    - TWITTER_ACCESS_TOKEN_SECRET=YOUR_ACCESS_TOKEN_SECRET
    - TWITTER_CONSUMER_KEY=YOUR_CONSUMER_KEY
    - TWITTER_CONSUMER_SECRET=YOUR_CONSUMER_SECRET

script: coverage run -m unittest discover tests
after_success: coveralls
